version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - err113
    - errname
    - errcheck
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - ginkgolinter
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - grouper
    - iface
    - importas
    - intrange
    - lll
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - unconvert
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - govet
    - ineffassign
    - unused
    - forbidigo
    - gosec
    - nolintlint

  settings:

    errcheck:
      check-type-assertions: true
      check-blank: true

    forbidigo:
      forbid:
        - pattern: "^panic\\("
          msg: "us panic() with caution, leave a comment explaining why it's necessary"
        - pattern: "unsafe\\."
          msg: "use unsafe with caution, leave a comment explaining why it's necessary"

    govet:
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - atomicalign
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - findcall
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shadow
        - shift
        - sigchanyzer
        - slog
        - sortslice
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - timeformat
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite

    gocritic:
      enabled-checks:
        - sloppyReassign
        - nilValReturn
        - rangeValCopy
        - hugeParam

    gosec:
      severity: medium
      confidence: medium

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*\\.dev"
      - ".*_test\\.go$" # Exclude test files from linting, as it's purposefully insecure sometimes

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*\\.dev"

