linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - gocritic
    - lll
    - misspell
    - mnd
    - musttag
    - nilnil
    - nlreturn
    - tagliatelle
    - stylecheck
    - sqlclosecheck
    - asciicheck
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - err113
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forcetypeassert
    - whitespace
    - ginkgolinter
    - goconst
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - grouper
    - iface
    - importas
    - mirror
    - nakedret
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - unconvert
    - wastedassign
    - wrapcheck
    - wsl
    - intrange
linters-settings:
  govet:
    enable:
      - appends
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - deepequalerrors
      - defers
      - directive
      - errorsas
      - findcall
      - framepointer
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - reflectvaluecompare
      - shadow
      - shift
      - sigchanyzer
      - slog
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - timeformat
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite
