name: Go CI

on:
  push:
    branches:
      - main
      - master
      - dev
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on:
      - self-hosted
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m
